class URL(object):
    BASE_URL = "https://api.dubverse.ai"
    STAGE_URL = "https://poopy.dubverse.ai"
    ADMIN_PREFIX = "/red"
    VERSION = "/api/v3"
    USER_URL = "/user"
    SUBSCRIPION_URL = "/subscription"
    CONFIG_URL = "/config"
    PLAN_URL = "/plan"
    METADATA_URL = "/metadata"
    ACCESSLEVEL_URL = "/accesslevel"
    AUTH_URL = "/auth/login"
